apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.27
        # image: public.ecr.aws/kishorj/docker-2048:latest
        imagePullPolicy: Always
        name: docker-2048
        resources:
          requests:
            memory: "64Mi"
            # For CPU resource units, the quantity expression 0.1 is equivalent to the expression 100m, 
            # which can be read as "one hundred millicpu" or "one hundred millicores".
            cpu: "200m" 
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port-service
  namespace: default
  labels:
    app: nginx
spec:
  type: NodePort 
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 31000