apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: httpd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: httpd
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpd
    spec:
      containers:
      - image: httpd:2.4
        imagePullPolicy: Always
        name: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: httpd-node-port-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: httpd
