apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-1-2048-game
    new: change
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # changing this to alb will simply create a classic load balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing # internal | internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip # ip | instance
  name: app-1-2048-game-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 31111